### ISSUE TITLE
Assessment Review

### ISSUE THREAD

**Issue by rwarbelow** [Thymey/mod_0_skills#1]
**Part I: Creating Directories and Files; Initializing Git and Pushing to GitHub**

- [ ] Did you name and structure your directories and files correctly?

**Notes:**: There seems to be an extra `mod_0_skills` inside of another `mod_0_skills` directory. 

- [x] Did you make one initial commit?
- [x] Did you push your initial commit to Github?

**Part II: Top Down Design**

- [x] Did you break down larger processes into multiple smaller layers?
- [x] Did you add and commit your changes with a properly formatted commit message?
- [x] Did you push your changes to Github?

**Part III: Classes in a System** 

- [x] Did you structure and name your directories and files correctly?
- [ ] Did you correctly categorize attributes and methods for each class?

**Notes:** Described methods, but did not include method names. Try to think of actions/behaviors that the class could do. For example, on a `Dessert` object, you could have a `Heat` method. The heat method would change the IsHot and IsFrozen attributes. 

- [x] Did you correctly identify data types of attributes for each class?
- [ ] Did you add and commit each set of changes separately with a properly formatted commit message?

**Notes:** Added and committed all three classes together. 

- [x] Did you push your changes to Github?

**Assessment Results**
- [ ] Pass
- [x] Conditional pass: Fix notes above and resubmit. 
- [ ] Fail with recommend for Mod 0 repeat
